// 轻量 TOML 序列化 / 反序列化：覆盖训练配置所需的平铺 key/value 结构。

function tomlValue(value) {
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  if (Array.isArray(value)) {
    return '[ ' + value.map((item) => {
      if (typeof item === 'string') return '"' + item.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
      return String(item);
    }).join(', ') + ' ]';
  }
  if (typeof value === 'string') {
    return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
  }
  return String(value);
}

export function configToToml(config) {
  const lines = ['# Generated by LoRA ReScripts UI', '# ' + new Date().toISOString(), ''];
  for (const [key, val] of Object.entries(config)) {
    if (val === undefined || val === null) continue;
    lines.push(key + ' = ' + tomlValue(val));
  }
  return lines.join('\n') + '\n';
}

export function parseSimpleToml(text) {
  const result = {};
  const rawLines = text.split(/\r?\n/);
  const mergedLines = [];

  for (let i = 0; i < rawLines.length; i++) {
    let line = rawLines[i];
    if (/=\s*\[/.test(line) && !line.includes(']')) {
      while (i + 1 < rawLines.length && !rawLines[i].includes(']')) {
        i++;
        line += ' ' + rawLines[i].trim();
      }
    }
    mergedLines.push(line);
  }

  for (const raw of mergedLines) {
    const commentIdx = raw.indexOf('#');
    const quoteBeforeComment = commentIdx >= 0 ? (raw.slice(0, commentIdx).split('"').length - 1) % 2 : 0;
    const line = (quoteBeforeComment ? raw : (commentIdx >= 0 ? raw.slice(0, commentIdx) : raw)).trim();
    if (!line || line.startsWith('[')) continue;

    const eqIdx = line.indexOf('=');
    if (eqIdx < 1) continue;
    const key = line.slice(0, eqIdx).trim();
    const val = line.slice(eqIdx + 1).trim();

    if (val === 'true') { result[key] = true; continue; }
    if (val === 'false') { result[key] = false; continue; }

    if (val.startsWith('[')) {
      const inner = val.slice(1, val.lastIndexOf(']')).trim();
      if (!inner) { result[key] = []; continue; }
      const items = [];
      const re = /"((?:[^"\\]|\\.)*)"|([^,"\s]+)/g;
      let match;
      while ((match = re.exec(inner)) !== null) {
        if (match[1] !== undefined) {
          items.push(match[1].replace(/\\\\/g, '\\').replace(/\\"/g, '"'));
        } else if (match[2] !== undefined) {
          const n = Number(match[2]);
          items.push(Number.isNaN(n) ? match[2] : n);
        }
      }
      result[key] = items;
      continue;
    }

    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      result[key] = val.slice(1, -1).replace(/\\\\/g, '\\').replace(/\\"/g, '"').replace(/\\n/g, '\n');
      continue;
    }

    const num = Number(val);
    if (!Number.isNaN(num) && val !== '') { result[key] = num; continue; }
    result[key] = val;
  }

  return result;
}
